# config.py

# =========================================================================
# --- AEVO TESTNET CREDENTIALS ---
# REPLACE the placeholders below with the keys you generated and copied:
# =========================================================================

# The signature generated by running generate_key_final.py
AEVO_SIGNING_KEY = "0x6c233e4b127e574dc32b1a64b486836ed93578bb35811d93c8478f16d0193ba74939a5c2384793d8b0ca35abe8ed8ba54ac9141a538f97083805a42101e561df1c"

# The public address of your MetaMask wallet (e.g., 0xB23C...)
AEVO_WALLET_ADDRESS = "0xB23C6670cDbAE03B523FF34Be3123A29f26f791f" 

# The standard API Key and Secret generated from the Aevo Settings/API Keys page
AEVO_API_KEY = "fpTXzpZZ4PhdksBBtPqthUE3pt3Cx1mW"
AEVO_API_SECRET = "292ac84ce4a442b4e306e97886d4f4d963e057c7015655e382f0aa35c30c1024"


# =========================================================================
# --- BRIDGE PARAMETERS ---
# These define where your FastAPI server will run.
# =========================================================================

# The host address for your FastAPI web server
BRIDGE_HOST = "127.0.0.1" 

# The port for your FastAPI web server (where your browser connects)
BRIDGE_PORT = 8081 

# The name of the script containing the FastMCP server logic
MCP_SERVER_SCRIPT = "server.py"